version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Setup
          command: sudo apt install mingw-w64 scons -y
      - run: |
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      - run:
          name: Compile
          command: scons platform=windows precision=double
      - store_artifacts:
          path: bin

workflows:
  build-windows:
    jobs:
      - build
